#include <stdio.h>
#include "convert.h"

int main(int argc, char **argv) {
	printf("Tasks 1.1 - 1.2\n");
	printf("\n");
	BDD *var2_bdd = read_BDD("./bdds/var2.bdd");
	printf("Printing var2.bdd...\n");
	print_BDD(var2_bdd);
	printf("\n");
	BDD *var5_bdd = read_BDD("./bdds/var5.bdd");
	printf("Printing var5.bdd...\n");
	print_BDD(var5_bdd);
	printf("\n");
	printf("\n");
	printf("\n");
	printf("Tasks 1.3 - 1.4\n");
	printf("\n");
	crossbar *var2_cb = read_crossbar("./xbars/var2.xbar");
	printf("Printing var2.xbar...\n");
	print_crossbar(var2_cb);
	printf("\n");
	crossbar *var5_cb = read_crossbar("./xbars/var5.xbar");
	printf("Printing var5.xbar...\n");
	print_crossbar(var5_cb);
	printf("\n");
	printf("\n");
	printf("\n");
	printf("Task 1.5\n");
	printf("\n");
	printf("Used in Task 4.1");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("Tasks 2.1 - 2.2\n");
	printf("\n");
	printf("Printing truth table of var2.xbar...\n");
	print_crossbar_truth_table(var2_cb);
	free_crossbar(var2_cb);
	printf("\n");
	printf("Printing truth table of var5.xbar...\n");
	print_crossbar_truth_table(var5_cb);
	free_crossbar(var5_cb);
	printf("\n");
	printf("\n");
	printf("\n");
	printf("Tasks 2.3 - 2.4\n");
	printf("\n");
	printf("Printing truth table of var2.bdd...\n");
	print_BDD_truth_table(var2_bdd);
	free_BDD(var2_bdd);
	printf("\n");
	printf("Printing truth table of var5.bdd...\n");
	print_BDD_truth_table(var5_bdd);
	free_BDD(var5_bdd);
	printf("\n");
	printf("\n");
	printf("\n");
	printf("Task 3.1\n");
	printf("\n");
	printf("var2: ");
	check_equivalence("./bdds/var2.bdd", "./xbars/var2.xbar");
	printf("var5: ");
	check_equivalence("./bdds/var5.bdd", "./xbars/var5.xbar");
	printf("var10: ");
	check_equivalence("./bdds/var10.bdd", "./xbars/var10.xbar");
	printf("var15: ");
	check_equivalence("./bdds/var15.bdd", "./xbars/var15.xbar");
	printf("var20: ");
	check_equivalence("./bdds/var20.bdd", "./xbars/var20.xbar");
	printf("var25: ");
	check_equivalence("./bdds/var25.bdd", "./xbars/var25.xbar");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("Task 4.1 \n");
	printf("\n");
	printf("Converting var2.bdd to var2.xbar...\n");
	convert_BDD_to_crossbar("./bdds/var2.bdd", "./xbars2/var2.bdd");
	printf("\n");
	printf("Converting var5.bdd to var5.xbar...\n");
	convert_BDD_to_crossbar("./bdds/var5.bdd", "./xbars2/var5.bdd");
	printf("\n");
	printf("Converting var10.bdd to var10.xbar...\n");
	convert_BDD_to_crossbar("./bdds/var10.bdd", "./xbars2/var10.bdd");
	printf("\n");
	printf("Converting var15.bdd to var15.xbar...\n");
	convert_BDD_to_crossbar("./bdds/var15.bdd", "./xbars2/var15.bdd");
	printf("\n");
	printf("Converting var20.bdd to var20.xbar...\n");
	convert_BDD_to_crossbar("./bdds/var20.bdd", "./xbars2/var20.bdd");
	printf("\n");
	printf("Converting var25.bdd to var25.xbar...\n");
	convert_BDD_to_crossbar("./bdds/var25.bdd", "./xbars2/var25.bdd");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("Extra: Converting SOP expressions to crossbars\n");
	printf("\n");
	printf("Converting ex1.sop to ex1.xbar...\n");
	convert_SOP_to_crossbar("./sops/ex1.sop", "./sops/ex1.xbar");
	printf("\n");
	printf("Converting ex2.sop to ex2.xbar...\n");
	convert_SOP_to_crossbar("./sops/ex2.sop", "./sops/ex2.xbar");
	printf("\n");
	printf("Converting ex3.sop to ex3.xbar...\n");
	convert_SOP_to_crossbar("./sops/ex3.sop", "./sops/ex3.xbar");
	printf("\n");
	printf("Converting ex4.sop to ex4.xbar...\n");
	convert_SOP_to_crossbar("./sops/ex4.sop", "./sops/ex4.xbar");
	printf("\n");
	printf("Converting ex5.sop to ex5.xbar...\n");
	convert_SOP_to_crossbar("./sops/ex5.sop", "./sops/ex5.xbar");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("Extra: Converting general boolean expressions to crossbars\n");
	printf("\n");
	printf("Converting ex1.expr to ex1.xbar...\n");
	convert_expression_to_crossbar("./exprs/ex1.expr", "./exprs/ex1.xbar");
	printf("\n");
	printf("Converting ex2.expr to ex2.xbar...\n");
	convert_expression_to_crossbar("./exprs/ex2.expr", "./exprs/ex2.xbar");
	printf("\n");
	printf("Converting ex3.expr to ex3.xbar...\n");
	convert_expression_to_crossbar("./exprs/ex3.expr", "./exprs/ex3.xbar");
	printf("\n");
	printf("Converting ex4.expr to ex4.xbar...\n");
	convert_expression_to_crossbar("./exprs/ex4.expr", "./exprs/ex4.xbar");

	return 0;
}
